server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Service Routes (no authentication needed)
        - id: auth-service-register
          uri: http://localhost:8081
          predicates:
            - Path=/auth/register
          filters:
            - StripPrefix=0

        - id: auth-service-login
          uri: http://localhost:8081
          predicates:
            - Path=/auth/login
          filters:
            - StripPrefix=0

        # Protected Routes - Poll Management Service
        - id: poll-management-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/polls/**
          filters:
            - name: AuthenticationFilter

        # Protected Routes - Vote Service
        - id: vote-service
          uri: http://localhost:8083
          predicates:
            - Path=/votes/**
          filters:
            - name: AuthenticationFilter

# Service URLs
services:
  auth-service:
    url: http://localhost:8081
    validate-endpoint: /auth/validate-token

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.democratizeddata: DEBUG