server:
  port: 8080

jwt:
  secret: secret-key

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Service Routes (no authentication needed)
        - id: auth-service-register
          uri: http://localhost:8081
          predicates:
            - Path=/auth/register
          filters:
            - StripPrefix=0

        - id: auth-service-login
          uri: http://localhost:8081
          predicates:
            - Path=/auth/login
          filters:
            - StripPrefix=0

        # Protected Routes - Poll Management Service
        - id: poll-management-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/polls/**
          filters:
            - name: Auth

        # Protected Routes - Vote Service
        - id: vote-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/votes/**
          filters:
            - name: Auth

      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

# Service URLs configuration
services:
  auth-service:
    url: http://localhost:8081
    validate-endpoint: /auth/validate


  poll-management-service:
    url: http://localhost:8082
  vote-service:
    url: http://localhost:8083

# Management endpoints for actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.democratizedData.gateway: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
